// currencyResult
export const SET_CURRENCY_RESULT = 'SET_CURRENCY_RESULT';
export const CLEAR_CURRENCY_RESULT = 'CLEAR_CURRENCY_RESULT';

// workingDays
export const SET_WORKING_DAYS = 'SET_WORKING_DAYS';
export const CLEAR_WORKING_DAYS = 'CLEAR_WORKING_DAYS';
